FROM mysql:8.0
ENV MYSQL_ROOT_PASSWORD=ExpenseApp@1 \
    MYSQL_DATABASE=transactions \
    MYSQL_USER=expense \
    MYSQL_PASSWORD=ExpenseApp@1
# mysql provide set of options to create database,users,etc we can use those options

# ADD scripts/*.sql /etc/mysql/mysql.conf.d

# or we can place our scripts into specified location
